alias btc-logs='docker logs bitcoind --tail 10 -f' 
alias lnd-logs='docker logs lightning --tail 10 -f' 
alias btc-cli='docker run --rm --network container:bitcoind -v /scratch/bitcoin/mainnet/bitcoind:/data jr0sco/bitcoind:latest su bitcoin -c bitcoin-cli $@' 
alias lnd-cli='docker run --rm --network container:lightning -v /scratch/bitcoin/mainnet/clightning:/data jr0sco/lnd:latest lightning-cli $@' 